name: example 
version: 0.0.1
# repository: https://github.com/definev/dart_vcd
publish_to: none

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  dart_vcd:
    path: ../

dev_dependencies: