name: dart_vcd
description: Read and write VCD (Value Change Dump) files
version: 0.0.1
# repository: https://github.com/definev/dart_vcd

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
